services:
  mysql:
    image: mysql:8.0
    env_file:
      - .env.docker
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ] # 10초마다 핑을 날려 DB 상태 확인
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
    volumes:
      - ./logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: